-- AlterTable
ALTER TABLE `session` ADD COLUMN `Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `durationMin` INTEGER NULL,
    ADD COLUMN `sessionType` ENUM('SPARRING', 'FIGHT') NULL,
    ADD COLUMN `title` VARCHAR(191) NULL;
