-- AlterTable
ALTER TABLE `tag` ADD COLUMN `athleteId` INTEGER NULL,
    ADD COLUMN `category` ENUM('TECHNICAL_ERROR', 'TECHINCAL_STRENGTH', 'TACTICAL_DECISION', 'OFFENSIVE', 'DEFENSIVE', 'PHYSICAL', 'MENTAL') NULL;

-- AddForeignKey
ALTER TABLE `Tag` ADD CONSTRAINT `Tag_athleteId_fkey` FOREIGN KEY (`athleteId`) REFERENCES `Athlete`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
