// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

console.log("Prisma DB URL form env:", env("MYSQL_DATABASE_URL"));

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: env("MYSQL_DATABASE_URL"),
  },
});
